In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [4]:
student = pd.read_csv("student_ml_dataset_100_records.csv")

student.head()

,StudentID,Name,Study_Hours,Attendance_,Previous_Score,Internet_Access,Extracurricular,FinalGrade
0,101,Student_1,6,97,67,Yes,No,64
1,102,Student_2,8,65,77,Yes,No,72
2,103,Student_3,-3,82,91,Yes,Yes,83
3,104,Student_4,8,96,71,Yes,Yes,66
4,105,Student_5,6,75,70,No,No,60

In [5]:
print("Dataset Shape:", student.shape)
print("No of Rows:", student.shape[0])
print("No of Columns:", student.shape[1])

print("\nColumn Names:")
print(student.columns)

print("\nDataset Information:")
student.info()

print("\nStatistical Summary:")
print(student.describe().transpose())

Dataset Shape: (100, 8)
No of Rows: 100
No of Columns: 8

Column Names:
Index(['StudentID', 'Name', 'Study_Hours', 'Attendance_', 'Previous_Score',
       'Internet_Access', 'Extracurricular', 'FinalGrade'],
      dtype='object')

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   StudentID        100 non-null    int64
 1   Name             100 non-null    object
 2   Study_Hours      100 non-null    int64
 3   Attendance_      100 non-null    int64
 4   Previous_Score   100 non-null    int64
 5   Internet_Access  100 non-null    object
 6   Extracurricular  100 non-null    object
 7   FinalGrade       100 non-null    int64
dtypes: int64(5), object(3)
memory usage: 6.4+ KB

Statistical Summary:
                count    mean        std    min     25%    50%     75%    max
StudentID       100.0  150.50  29.011492  101.0  125.75  150.5  175.25  200.0
Study_Hours     100.0    6.03   2.668390   -3.0    4.00    6.0    8.00   10.0
Attendance_     100.0   82.02  10.969176   65.0   72.75   81.0   92.00  105.0
Previous_Score  100.0   77.14  14.758678   50.0   66.00   75.0   91.25  100.0
FinalGrade      100.0   67.84   8.801653   51.0   60.00   67.0   75.00   86.0

In [6]:
student.columns = (
    student.columns
    .str.strip()
    .str.replace(' ', '_')
    .str.replace(r'[%()]', '', regex=True)
)

print(student.columns)

Index(['StudentID', 'Name', 'Study_Hours', 'Attendance_', 'Previous_Score',
       'Internet_Access', 'Extracurricular', 'FinalGrade'],
      dtype='object')

In [7]:
student.loc[
    student['Study_Hours'] < 0,
    'Study_Hours'
] = np.nan

student.loc[
    student['Attendance_'] > 100,
    'Attendance_'
] = np.nan

In [8]:
print(student.isnull().sum())

StudentID          0
Name               0
Study_Hours        1
Attendance_        1
Previous_Score     0
Internet_Access    0
Extracurricular    0
FinalGrade         0
dtype: int64

In [9]:
student = student.drop(
    columns=['StudentID', 'Name']
)

print(student.columns)

Index(['Study_Hours', 'Attendance_', 'Previous_Score', 'Internet_Access',
       'Extracurricular', 'FinalGrade'],
      dtype='object')

In [10]:
num_cols = student.select_dtypes(
    include='number'
).columns

print("Before numerical columns")
print("*" * 30)
print(student[num_cols].isnull().sum())

for col in num_cols:
    student[col] = student[col].fillna(
        student[col].median()
    )

print("\nAfter numerical columns")
print("*" * 30)
print(student[num_cols].isnull().sum())

Before numerical columns
******************************
Study_Hours       1
Attendance_       1
Previous_Score    0
FinalGrade        0
dtype: int64

After numerical columns
******************************
Study_Hours       0
Attendance_       0
Previous_Score    0
FinalGrade        0
dtype: int64

In [11]:
cat_cols = student.select_dtypes(
    include='object'
).columns

print("Before categorical columns")
print("*" * 30)
print(student[cat_cols].isnull().sum())

for col in cat_cols:
    student[col] = student[col].fillna(
        student[col].mode()[0]
    )

print("\nAfter categorical columns")
print("*" * 30)
print(student[cat_cols].isnull().sum())

Before categorical columns
******************************
Internet_Access    0
Extracurricular    0
dtype: int64

After categorical columns
******************************
Internet_Access    0
Extracurricular    0
dtype: int64

In [12]:
print(student.isnull().sum())

Study_Hours        0
Attendance_        0
Previous_Score     0
Internet_Access    0
Extracurricular    0
FinalGrade         0
dtype: int64

In [13]:
print(
    "Number of duplicate rows:",
    student.duplicated().sum()
)

student = student.drop_duplicates()

print(
    "Shape after removing duplicates:",
    student.shape
)

Number of duplicate rows: 0
Shape after removing duplicates: (100, 6)

In [14]:
print("Categorical Columns:")
print(cat_cols)

le = LabelEncoder()

for col in cat_cols:
    student[col] = le.fit_transform(
        student[col]
    )

student.head()

Categorical Columns:
Index(['Internet_Access', 'Extracurricular'], dtype='object')

,Study_Hours,Attendance_,Previous_Score,Internet_Access,Extracurricular,FinalGrade
0,6.0,97.0,67,1,0,64
1,8.0,65.0,77,1,0,72
2,6.0,82.0,91,1,1,83
3,8.0,96.0,71,1,1,66
4,6.0,75.0,70,0,0,60

In [15]:
X = student.drop(
    'FinalGrade',
    axis=1
)

y = student['FinalGrade']

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
   Study_Hours  Attendance_  Previous_Score  Internet_Access  Extracurricular
0          6.0         97.0              67                1                0
1          8.0         65.0              77                1                0
2          6.0         82.0              91                1                1
3          8.0         96.0              71                1                1
4          6.0         75.0              70                0                0

Target:
0    64
1    72
2    83
3    66
4    60
Name: FinalGrade, dtype: int64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (80, 5)
X_test : (20, 5)
y_train: (80,)
y_test : (20,)

In [17]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [18]:
print(
    "Training data shape:",
    X_train_scaled.shape
)

print(
    "Testing data shape:",
    X_test_scaled.shape
)

print("\nMissing values in X_train:")
print(X_train.isnull().sum().sum())

print("\nMissing values in X_test:")
print(X_test.isnull().sum().sum())

print("\nFirst 5 rows of scaled training data:")
print(X_train_scaled[:5])

Training data shape: (80, 5)
Testing data shape: (20, 5)

Missing values in X_train:
0

Missing values in X_test:
0

First 5 rows of scaled training data:
[[ 0.02369296  1.45195959 -0.74040542 -0.92761259 -1.22474487]
 [-0.35539436 -1.4447179   0.75742624  1.07803625  0.81649658]
 [-1.49265632  0.00362085 -0.80848868 -0.92761259 -1.22474487]
 [ 0.7818676  -1.54127381 -1.82973754  1.07803625 -1.22474487]
 [-0.73448168 -1.4447179   1.02975926 -0.92761259 -1.22474487]]

In [19]:
print(
    "The dataset has been successfully preprocessed."
)

print(
    "Missing and invalid values have been handled, "
    "categorical variables have been encoded, "
    "and numerical features have been standardized "
    "without data leakage."
)

print(
    "The Student Performance dataset has been "
    "successfully cleaned and transformed."
)

print(
    "The preprocessed training and testing data "
    "are now ready to be used as input for a "
    "Machine Learning algorithm."
)

The dataset has been successfully preprocessed.
Missing and invalid values have been handled, categorical variables have been encoded, and numerical features have been standardized without data leakage.
The Student Performance dataset has been successfully cleaned and transformed.
The preprocessed training and testing data are now ready to be used as input for a Machine Learning algorithm.

In [20]:
student.to_csv(
    "cleaned_student_performance.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.