In [1]:

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
dataset = "/content/student_performance_updated_1000.csv"
student = pd.read_csv(dataset)
student.head()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True

In [3]:

print("Dataset Shape:",student.shape)
print("No of Rows",student.shape[0])
print("No of Columnss",student.shape[1])

Dataset Shape: (1000, 12)
No of Rows 1000
No of Columnss 12

In [4]:

print("Dataset Shape:",student.shape)
print("No of Rows",student.shape[0])
print("No of Columnss",student.shape[1])

Dataset Shape: (1000, 12)
No of Rows 1000
No of Columnss 12

In [5]:

print("\nColumn Names:")
print(student.columns)

Column Names:
Index(['StudentID', 'Name', 'Gender', 'AttendanceRate', 'StudyHoursPerWeek',
       'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport',
       'FinalGrade', 'Study Hours', 'Attendance (%)', 'Online Classes Taken'],
      dtype='object')

In [6]:

print("\nDataset Information:")
print(student.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  960 non-null    float64
 1   Name                       966 non-null    object
 2   Gender                     952 non-null    object
 3   AttendanceRate             960 non-null    float64
 4   StudyHoursPerWeek          950 non-null    float64
 5   PreviousGrade              967 non-null    float64
 6   ExtracurricularActivities  957 non-null    float64
 7   ParentalSupport            978 non-null    object
 8   FinalGrade                 960 non-null    float64
 9   Study Hours                976 non-null    float64
 10  Attendance (%)             959 non-null    float64
 11  Online Classes Taken       975 non-null    object
dtypes: float64(8), object(4)
memory usage: 93.9+ KB
None

In [7]:

print("\nStatistical Summary:")
student.describe().transpose()

Statistical Summary:

,count,mean,std,min,25%,50%,75%,max
StudentID,960.0,5416.019792,2653.748319,1.0,3113.5,5396.5,7754.75,9998.0
AttendanceRate,960.0,85.510417,7.332125,70.0,82.0,88.0,91.00,95.0
StudyHoursPerWeek,950.0,17.630526,6.272132,8.0,12.0,18.0,22.00,30.0
PreviousGrade,967.0,77.598759,10.006640,60.0,70.0,78.0,86.00,90.0
ExtracurricularActivities,957.0,1.520376,1.046439,0.0,1.0,1.0,2.00,3.0
FinalGrade,960.0,80.030208,9.493652,62.0,72.0,80.0,88.00,92.0
Study Hours,976.0,2.406967,1.620267,-5.0,1.2,2.5,3.70,5.0
Attendance (%),959.0,77.248175,19.298148,50.0,63.0,76.0,89.00,200.0

In [8]:
student.columns = (
    student.columns
    .str.strip()
    .str.replace(' ', '_')
    .str.replace(r'[%()]', '', regex=True)
)

print(student.columns)

Index(['StudentID', 'Name', 'Gender', 'AttendanceRate', 'StudyHoursPerWeek',
       'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport',
       'FinalGrade', 'Study_Hours', 'Attendance_', 'Online_Classes_Taken'],
      dtype='object')

In [9]:
# Replace Invalid Values with NaN
student.loc[student['Study_Hours'] < 0, 'Study_Hours'] = np.nan

student.loc[student['Attendance_'] > 100, 'Attendance_'] = np.nan

In [10]:
print(student.isnull().sum())

StudentID                    40
Name                         34
Gender                       48
AttendanceRate               40
StudyHoursPerWeek            50
PreviousGrade                33
ExtracurricularActivities    43
ParentalSupport              22
FinalGrade                   40
Study_Hours                  34
Attendance_                  51
Online_Classes_Taken         25
dtype: int64

In [11]:

student = student.drop(columns=['StudentID', 'Name'])

print(student.columns)

Index(['Gender', 'AttendanceRate', 'StudyHoursPerWeek', 'PreviousGrade',
       'ExtracurricularActivities', 'ParentalSupport', 'FinalGrade',
       'Study_Hours', 'Attendance_', 'Online_Classes_Taken'],
      dtype='object')

In [12]:
num_cols = student.select_dtypes(include='number').columns
print("Before numerical columns")
print("*" * 30)
print(student[num_cols].isnull().sum())

for col in num_cols:
    student[col] = student[col].fillna(student[col].median())

print("\n After numerical columns")
print("*" * 30)
print(student[num_cols].isnull().sum())

Before numerical columns
******************************
AttendanceRate               40
StudyHoursPerWeek            50
PreviousGrade                33
ExtracurricularActivities    43
FinalGrade                   40
Study_Hours                  34
Attendance_                  51
dtype: int64

 After numerical columns
******************************
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
FinalGrade                   0
Study_Hours                  0
Attendance_                  0
dtype: int64

In [13]:
cat_cols = student.select_dtypes(include='object').columns

print("Before numerical columns")
print("*" * 30)
print(student[cat_cols].isnull().sum())

for col in cat_cols:
    student[col] = student[col].fillna(student[col].mode()[0])

print("After numerical columns")
print("*" * 30)
print(student[cat_cols].isnull().sum())

Before numerical columns
******************************
Gender                  48
ParentalSupport         22
Online_Classes_Taken    25
dtype: int64
After numerical columns
******************************
Gender                  0
ParentalSupport         0
Online_Classes_Taken    0
dtype: int64

/tmp/ipykernel_1748/2678543693.py:8: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  student[col] = student[col].fillna(student[col].mode()[0])

In [14]:

# Check data set after handling missing values
student.isnull().sum()

Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
FinalGrade                   0
Study_Hours                  0
Attendance_                  0
Online_Classes_Taken         0
dtype: int64

In [15]:

print("Number of duplicate rows:", student.duplicated().sum())

student = student.drop_duplicates()

print("Shape after removing duplicates:", student.shape)

Number of duplicate rows: 0
Shape after removing duplicates: (1000, 10)

In [16]:

print("Categorical Columns:")
print(cat_cols)

Categorical Columns:
Index(['Gender', 'ParentalSupport', 'Online_Classes_Taken'], dtype='object')

In [17]:
le = LabelEncoder()

for col in cat_cols:
    student[col] = le.fit_transform(student[col])

student.head()

,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study_Hours,Attendance_,Online_Classes_Taken
0,1,85.0,15.0,78.0,1.0,0,80.0,4.8,59.0,0
1,0,90.0,20.0,85.0,2.0,2,87.0,2.2,70.0,1
2,1,78.0,10.0,65.0,0.0,1,68.0,4.6,92.0,0
3,1,92.0,25.0,90.0,3.0,0,92.0,2.9,96.0,0
4,0,88.0,18.0,82.0,2.0,2,85.0,4.1,97.0,1

In [18]:

X = student.drop('FinalGrade', axis=1)  # Feature
y = student['FinalGrade'] # Target

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=42
                                                    )

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (800, 9)
X_test : (200, 9)
y_train: (800,)
y_test : (200,)

In [20]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [21]:

print("Training data shape:", X_train_scaled.shape)
print("Testing data shape :", X_test_scaled.shape)

Training data shape: (800, 9)
Testing data shape : (200, 9)

In [22]:
print("\nMissing values in X_train:")
print(X_train.isnull().sum().sum())

Missing values in X_train:
0

In [23]:

print("\nMissing values in X_test:")
print(X_test.isnull().sum().sum())

Missing values in X_test:
0

In [24]:

print("\nFirst 5 rows of scaled training data:")
print(X_train_scaled[:5])

First 5 rows of scaled training data:
[[ 0.87299172  0.72376272  0.69798871 -0.05007211  1.47116139  1.24123319
  -1.05416041 -1.40381823 -1.02275892]
 [ 0.87299172 -2.23973074 -1.59183952  0.05133976  1.47116139  0.03761313
   0.78115695 -0.08355854  0.97774752]
 [-1.14548624  0.72376272 -0.4469254  -0.75995518  1.47116139  1.24123319
  -1.2659278  -1.19535618 -1.02275892]
 [ 0.87299172  0.72376272  0.69798871 -1.77407385 -1.43962784  0.03761313
   1.27528086  1.51465056 -1.02275892]
 [ 0.87299172  0.30040651  0.37087039 -0.75995518 -1.43962784 -1.16600694
  -0.0659126  -1.05638147  0.97774752]]

In [25]:

student.to_csv("cleaned_student_performance.csv", index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [26]:

cleaned_student = pd.read_csv("cleaned_student_performance.csv")

print("Cleaned Dataset Shape:", cleaned_student.shape)
print(cleaned_student.head())

Cleaned Dataset Shape: (1000, 10)
   Gender  AttendanceRate  StudyHoursPerWeek  PreviousGrade  \
0       1            85.0               15.0           78.0
1       0            90.0               20.0           85.0
2       1            78.0               10.0           65.0
3       1            92.0               25.0           90.0
4       0            88.0               18.0           82.0

   ExtracurricularActivities  ParentalSupport  FinalGrade  Study_Hours  \
0                        1.0                0        80.0          4.8
1                        2.0                2        87.0          2.2
2                        0.0                1        68.0          4.6
3                        3.0                0        92.0          2.9
4                        2.0                2        85.0          4.1

   Attendance_  Online_Classes_Taken
0         59.0                     0
1         70.0                     1
2         92.0                     0
3         96.0                     0
4         97.0                     1